kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-sc-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-sc-storage
  local:
    path: /Users/gustavochaves/Formacao_DevOps/Laboratorios/Kubernetes-jenkins/pv-jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: jenkins-sc-storage
  resources:
    requests:
      storage: 1Gi